### Vectorization

In [2]:
import numpy as np
import math

In [3]:
a=np.array([1,2,3,4])

In [4]:
math.factorial(3)

6

In [5]:
math.factorial(a)

TypeError: only integer scalar arrays can be converted to a scalar index

In [6]:
a

array([1, 2, 3, 4])

In [8]:
for i in a:
  print(math.factorial(i))

1
2
6
24


In [9]:
fast_factorial=np.vectorize(math.factorial)

In [10]:
fast_factorial(a)

array([ 1,  2,  6, 24])

### Shallow vs deepcopy

In [11]:
l1=[1,2,3,4]

In [12]:
l2=l1 #shallow copy

In [13]:
l1[0]=20
l1

[20, 2, 3, 4]

In [14]:
l2

[20, 2, 3, 4]

In [15]:
print(id(1),id(2))

10757736 10757768


In [17]:
l1=[1,2,3,4]
l2=l1.copy()#deepcopy
l1[0]=20
print(l1,l2)
print(id(l1),id(l2))

[20, 2, 3, 4] [1, 2, 3, 4]
137572572264768 137572962433984


In [18]:
l2[1]=30
l2

[1, 30, 3, 4]

### Array

In [19]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [20]:
b= a+1 #new copy of array =>new memory => deep copy

In [21]:
a

array([1, 2, 3, 4])

In [22]:
b

array([2, 3, 4, 5])

In [23]:
c=a#shallow copy

In [24]:
a[0]=100
a

array([100,   2,   3,   4])

In [25]:
c

array([100,   2,   3,   4])

In [26]:
c[1]

np.int64(2)

In [27]:
a

array([100,   2,   3,   4])

In [28]:
a**2

array([10000,     4,     9,    16])

In [29]:
a

array([100,   2,   3,   4])

In [30]:
a=np.array([1,2,3,4])
b=a.reshape(2,2)#shallow copy
b

array([[1, 2],
       [3, 4]])

In [31]:
a

array([1, 2, 3, 4])

In [32]:
a[0]=100
a

array([100,   2,   3,   4])

In [33]:
b

array([[100,   2],
       [  3,   4]])

In [34]:
np.shares_memory(a,b)

True

In [35]:
#shallow & deep copy using inbuild functions of numpy

In [36]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
#copy => deep copy
b = arr.copy()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
np.shares_memory(arr,b)

False

In [39]:
#shallow copy
c = arr.view()


In [40]:
np.shares_memory(arr,c)

True

In [41]:
a = np.array([0,1,2,3,4,5])
a


array([0, 1, 2, 3, 4, 5])

In [42]:
a%1 == 0

array([ True,  True,  True,  True,  True,  True])

In [43]:
b = a[a%1 == 0]
b

array([0, 1, 2, 3, 4, 5])

In [44]:
np.shares_memory(a,b)

False

In [45]:
b[0] = 10
a[:2]

array([0, 1])

### Array Splliting

In [46]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
np.split(a,3) #deep copy


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [48]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
np.split(a,4)

ValueError: array split does not result in an equal division

In [50]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.split(a,(3,5,6)) #unequal length array

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]

In [52]:
np.split(a,(4,))

[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8])]

### 2D array

In [53]:
a = np.arange(16).reshape(4,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.split(a,2,axis=1)


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [55]:
np.split(a,2) #default is axis =0

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [63]:
np.split?

In [57]:
np.split(a,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [58]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [62]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [61]:
np.vsplit(a,4)


[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

### Merging or stacking

In [64]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [65]:
b = np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [66]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
np.hstack((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.vstack((a,a,a))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [69]:
np.hstack((a,a,a))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

Broadcasting

Rule 1 : If two array differ in the number of dimensions, the shape of one with fewer dimensions is padded with ones on its
leading( Left Side).  
Rule 2 : If the shape of two arrays doesnt match in any dimensions, the array with shape equal to 1 is stretched to match
the other shape.


In [70]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [71]:
np.vstack((a,a,a))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [72]:
np.tile(a,(3,1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [73]:
np.tile(a,(3,2))


array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [74]:
a = np.arange(0,40,10)

In [75]:
a.ndim

1

In [76]:
a.T

array([ 0, 10, 20, 30])

In [77]:
a = np.tile(a,(3,1))

In [78]:
a = a.T

In [79]:
b = np.arange(3)
b

array([0, 1, 2])

In [80]:
b

array([0, 1, 2])

In [81]:
b = np.tile(b,(4,1))
b #deep copy

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [82]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [83]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [84]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [85]:
a = np.arange(8).reshape(2,4)
b = np.arange(16).reshape(4,4)
a,b

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [86]:
a+b

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

In [87]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [88]:
a.shape

(4,)

In [89]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (4,3) 

In [91]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
a+b

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])