In [1]:
import numpy as np

In [2]:
arr=np.arange(1,20)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### 2d arrays


In [4]:
lst=[[1,2,3],[1,2,3]]
print(lst)
print(len(lst))
arr=np.array(lst)
print(arr)
print(arr.shape)
print(arr.size)

[[1, 2, 3], [1, 2, 3]]
2
[[1 2 3]
 [1 2 3]]
(2, 3)
6


In [5]:
arr=np.arange(12)
print(arr)
print(arr.size)
print(arr.shape)
print(len(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
(12,)
12


In [6]:
print(arr.reshape(3,4))
print("-"*25)
print(arr.reshape(4,3))
print("-"*25)
print(arr.reshape(6,2))
print("-"*25)
print(arr.reshape(2,6))
print("-"*25)
print(arr.reshape(12,1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-------------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
-------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
-------------------------
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [7]:
print(arr)
print(arr.reshape(4,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


ValueError: cannot reshape array of size 12 into shape (4,4)

In [8]:
print(arr)
print(arr.reshape(3,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


ValueError: cannot reshape array of size 12 into shape (3,2)

In [9]:
print(arr)
print(arr.shape)
print(arr.reshape(3,-1))#-1 for unknown dimension
print("-"*25)
print(arr.reshape(-1,4))#-1 for unknown dimension

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print(arr)
print(arr.shape)
print(arr.reshape(3,2,-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [11]:
print(arr)
print(arr.shape)
print(arr.reshape(3,-1, -1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


ValueError: can only specify one unknown dimension

In [12]:
print(arr)
print(arr.shape)
print(arr.reshape(5,-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


ValueError: cannot reshape array of size 12 into shape (5,newaxis)

### Transpose

In [13]:
print(arr)
print("-"*25)
arr2D = arr.reshape(4,3)
print(arr2D)
print(arr2D.shape)
print("-"*25, "TRANSPOSE")
print(arr2D.T)
print(arr2D.T.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
------------------------- TRANSPOSE
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
(3, 4)


### Accessing of elements and slicing

In [14]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting 1 row:")
print(arr2D[0])
print(arr2D[1])
print(arr2D[2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting 1 row:
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [15]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting 1 element(eg:7):")
print(arr2D[1])
print(arr2D[1][3])# arr[row_ind][col_ind]
print(arr2D[1,3])# arr[row_ind,col_ind]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting 1 element(eg:7):
[4 5 6 7]
7
7


In [16]:
arr1D = np.arange(12)
print(arr1D)
print("Getting 1 element(eg:7):")
print(arr1D[7])
print("Getting multiple lements:")
print(arr1D[[7,0,10,3,-1]])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Getting 1 element(eg:7):
7
Getting multiple lements:
[ 7  0 10  3 11]


In [17]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting 1 element(eg:7):")
print(arr2D[1,3])# arr[row_ind,col_ind]
print("Getting multiple lements:")
print(arr2D[[1,2,0],[3,2,1]])# arr[[row_ind],[col_ind]]>>(1,3),(2,2),(0,1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting 1 element(eg:7):
7
Getting multiple lements:
[ 7 10  1]


In [18]:
arr1D = np.arange(12)
print(arr1D)
print("Getting 1 element(eg:7):")
print(arr1D[7])
print("Getting multiple lements:")
print(arr1D[[7,0,10,3,-1]])
print("Slicing")
print(arr1D[1:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Getting 1 element(eg:7):
7
Getting multiple lements:
[ 7  0 10  3 11]
Slicing
[1 2]


In [21]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting 1 element(eg:7):")
print(arr2D[1,3])# arr[row_ind,col_ind]
print("Getting multiple lements:")
print(arr2D[[1,2,0],[3,2,1]])# arr[[row_ind],[col_ind]]>>(1,3),(2,2),(0,1)
print("Slicing")
print(arr2D[1:]) # no end is given
print("-"*25)
print(arr2D[1:2]) # start=1, end=2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting 1 element(eg:7):
7
Getting multiple lements:
[ 7 10  1]
Slicing
[[ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[4 5 6 7]]


In [23]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting multiple lements:")
print(arr2D[[1,2,0],[3,2,1]])# arr[[row_ind],[col_ind]]>>(1,3),(2,2),(0,1)
print("Slicing")
print(arr2D[1:]) # no end is given
print("-"*25)
print(arr2D[1:2]) # start=1, end=2
print("Slicing rows and cols")
print(arr2D[1:, 0::2]) # arr[row_slicing, col_slicing]
print("get 1 col")
print(arr2D[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting multiple lements:
[ 7 10  1]
Slicing
[[ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[4 5 6 7]]
Slicing rows and cols
[[ 4  6]
 [ 8 10]]
get 1 col
[ 2  6 10]


In [24]:
a = [1,2,3,4,5]
b = [8,7,6]
print(a)
print(b)
print("-"*25)
print(a[3:])
print(b[::-2])
print("-"*25)
a[3:] = b[::-2]
print(a)

[1, 2, 3, 4, 5]
[8, 7, 6]
-------------------------
[4, 5]
[6, 8]
-------------------------
[1, 2, 3, 6, 8]


### Fancy indexing(Masking)

In [25]:
arr1D = np.arange(12)
print(arr1D)
print("Mask")
print(arr1D%3==0)
print("Masking")
print(arr1D[arr1D%3==0])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Mask
[ True False False  True False False  True False False  True False False]
Masking
[0 3 6 9]


In [26]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Mask")
print(arr2D%3==0)
print("Masking")
print(arr2D[arr2D%3==0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mask
[[ True False False  True]
 [False False  True False]
 [False  True False False]]
Masking
[0 3 6 9]


In [27]:
a = np.array([0,1,2,3,4,5])
print(a)
mask = (a%2 == 0)
print(mask)
print(a[mask])
a[mask] = -1
print(a)

[0 1 2 3 4 5]
[ True False  True False  True False]
[0 2 4]
[-1  1 -1  3 -1  5]


### Aggregate Functions(1D)

In [28]:
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [30]:
# sum
print(np.sum(a))

55


In [31]:
# mean
np.mean(a)

np.float64(5.0)

In [32]:
# min
np.min(a)

np.int64(0)

In [33]:
# max
np.max(a)

np.int64(10)

In [34]:
# median
np.median(a)

np.float64(5.0)

Aggregate Functions (2D)

In [35]:
a2 = np.arange(12).reshape(4,3)
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
# sum
print(np.sum(a2)) #  axis=None[default]
print(np.sum(a2, axis=0)) # go along the axis=0
print(np.sum(a2, axis=1)) # go along the axis=1

66
[18 22 26]
[ 3 12 21 30]


In [37]:
# mean
print(np.mean(a2)) #  axis=None[default]
print(np.mean(a2, axis=0)) # go along the axis=0
print(np.mean(a2, axis=1)) # go along the axis=1

5.5
[4.5 5.5 6.5]
[ 1.  4.  7. 10.]


In [38]:
print(np.sum(a2, axis=0)) # go along the axis=0
print(np.sum(a2[:,0]))
print(np.sum(a2[:,1]))
print(np.sum(a2[:,2]))

[18 22 26]
18
22
26


### Logical Operators

In [39]:
a = np.array([1,2,7,3,4,7,8,9,7,6,7,12])
print(a.shape)
print(a)

(12,)
[ 1  2  7  3  4  7  8  9  7  6  7 12]


In [40]:
print(a==7) # mask
print(a[a==7]) # masking

[False False  True False False  True False False  True False  True False]
[7 7 7 7]


In [41]:
print(a%3==0)
print(a%2==0)
# masks
print((a%3==0 )& (a%2==0)) # and
print((a%3==0 )| (a%2==0)) # or

[False False False  True False False False  True False  True False  True]
[False  True False False  True False  True False False  True False  True]
[False False False False False False False False False  True False  True]
[False  True False  True  True False  True  True False  True False  True]


In [42]:
print(a[(a%3==0 )& (a%2==0)])

[ 6 12]


In [43]:
print(a[(a%3==0 ) | (a%2==0)])

[ 2  3  4  8  9  6 12]


In [44]:
# any
print("any: this will give you True if even one True is present")
print(np.any(a==7)) # is ANY value equal to 7
print(np.any(a==0)) # is ANY value equal to 0

# all
print("all: this will give you False if even one False is present")
print(np.all(a==7)) # are ALL the values equal to 7
print(np.all(a%1==0)) # are ALL the values divisible by 1

any: this will give you True if even one True is present
True
False
all: this will give you False if even one False is present
False
True


In [45]:
# where>> taken input as Mask, gives indeces where mask is True
print(np.where(a==7))

(array([ 2,  5,  8, 10]),)


In [55]:
a2D = a.reshape(4,3)
print(a2D)

[[ 1  2  7]
 [ 3  4  7]
 [ 8  9  7]
 [ 6  7 12]]


In [56]:
print(np.where(a2D==7))

(array([0, 1, 2, 3]), array([2, 2, 2, 1]))


In [57]:
a2D[np.where(a2D==7)]

array([7, 7, 7, 7])

In [58]:
a = np.array([0,2,3])
b = np.array([1,3,5])
print(a>=b) # element level analysis/comparison

[False False False]


In [59]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0])
print(arr)
print(np.where(arr))

[ -3   4  27  34  -2   0 -45 -11   4   0]
(array([0, 1, 2, 3, 4, 6, 7, 8]),)


### Using fit-bit dataset

In [60]:
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 11.5MB/s]


In [62]:
data = np.loadtxt("/content/fit.txt", dtype=str)

/tmp/ipython-input-916140340.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt("/content/fit.txt", dtype=str)


In [63]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [64]:
data.shape

(96, 6)

In [65]:
date = data[:,0] # arr[row_index, col_inde]
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [66]:
steps = data[:,1].astype(int) # arr[row_index, col_inde]
steps

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [67]:
mood = data[:,2] # arr[row_index, col_inde]
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [68]:
calories = data[:,3].astype(int) # arr[row_index, col_inde]
calories

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [69]:
sleep = data[:,4].astype(int) # arr[row_index, col_inde]
sleep

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [70]:
active = data[:,5] # arr[row_index, col_inde]
active

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [71]:
happy_mask = mood=="Happy"
happy_mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [72]:
sad_mask = mood=="Sad"
sad_mask

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
        True,  True, False, False, False, False])

In [73]:
steps[happy_mask] # steps of days when I was happy

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [74]:
steps[happy_mask].mean()

np.float64(3392.725)

In [75]:
steps[sad_mask].mean()

np.float64(2103.0689655172414)

In [76]:
# when I steps>=4000, I am mostly happy
steps4k_mask = steps>=4000
steps4k_mask

array([ True,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False, False, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [77]:
mood[steps4k_mask] # mood wherever steps were >=4000

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [78]:
np.unique(mood[steps4k_mask])

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [79]:
np.unique(mood[steps4k_mask], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))