In [2]:
import numpy as np

## np.array()
is a function is used to create or convert a list into an array

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr)) #ndarray or also called as n-dimensional array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
lst=list(range(1000000))
arr=np.array(lst)

In [ ]:
%%time
sq_lst=[num**2 for num in lst]

CPU times: total: 78.1 ms
Wall time: 82.6 ms


In [ ]:
%%time
sq_arr = arr**2

CPU times: total: 0 ns
Wall time: 1 ms


-------------------------------------------------  
**array.dtype**   
used to give type of array  
**arr.ndim**  
used to give the dimensions of the array  


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))
pirnt(arr.ndim)

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>
1


---------------------------------
**arr.shape** give the shape of the array

In [ ]:
print(arr.shape)
print(type(arr.shape))

(5,)
<class 'tuple'>


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print(arr.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
int32


In [ ]:
print(type(arr))
print(arr.ndim)
print(arr[3])
print(arr[3][1])
print(arr.shape)

<class 'numpy.ndarray'>
2
[10 11 12]
11
(4, 3)


**arange()** range function in numpy world  
main difference is it can take float as its step value

In [ ]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr=np.arange(1,5,0.5)
print(arr)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
arr=np.arange(5)
print(arr)
print(arr[1:3])
arr[0]=123
arr[1:3]=0
print(arr)

print("-"*25)

lst=list(range(5))
print(lst)
print(lst[1:3])
lst[0]=123
lst[1:3]=0
print(lst)

[0 1 2 3 4]
[1 2]
[123   0   0   3   4]
-------------------------
[0, 1, 2, 3, 4]
[1, 2]


TypeError: can only assign an iterable

**Type Conversion**

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int32


In [ ]:
arr=np.array([1,2,3,4,5.123])
print(arr,arr.dtype)

[1.    2.    3.    4.    5.123] float64


In [ ]:
arr=np.array([1,"Ronaldo",3,4,5.123])
print(arr,arr.dtype)

['1' 'Ronaldo' '3' '4' '5.123'] <U32


**astype**

In [ ]:
arr=np.array([1,2,3,4,5],dtype=float)
print(arr,arr.dtype)
print(arr.astype(int))

[1. 2. 3. 4. 5.] float64
[1 2 3 4 5]


In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print(arr[2][1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8


In [4]:
arr=np.arange(10)
print(arr)
print(arr[2:7:2])
print(arr[2:7:-1])
print(arr[-2:-7:-1])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[]
[8 7 6 5 4]


In [5]:
a=np.array([0,1,2,3,4,5])
print(a)
print(a[4:])
a[4:]=10
print(a)

[0 1 2 3 4 5]
[4 5]
[ 0  1  2  3 10 10]


### Fancy indexing (Masking)

In [6]:
m1=np.arange(1,11)
print(m1)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
print(m1<6) #Here m1<6 is the mask

[ True  True  True  True  True False False False False False]


In [8]:
print(m1[m1<6]) #fancy indexing(Masking)

[1 2 3 4 5]


In [9]:
#Use masking to get only even numbers from m1
print(m1%2==0)
print(m1[m1%2==0])

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [10]:
a=np.array([1,2,3,4,5])
b=np.array([8,7,6])
print(a)
print(b)
print(a[2:])
print(b[::-1])
a[2:]=b[::-1]
print(a)

[1 2 3 4 5]
[8 7 6]
[3 4 5]
[6 7 8]
[1 2 6 7 8]


### Using Net Promoter Score dataset

In [12]:
# https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 7.81MB/s]


In [13]:
score=np.loadtxt("/content/survey.txt",dtype=int)
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [16]:
promoters_mask=score>=9
promoters=score[promoters_mask]
num_promoters = promoters.shape[0]
per_promoters=num_promoters/score.shape[0]*100
per_promoters=round(per_promoters,2)
per_promoters

52.19

In [19]:
detractors_mask=score<=6
detractors=score[detractors_mask]
num_detractors = detractors.shape[0]
per_detractor=num_detractors/score.shape[0]*100
per_detractor=round(per_detractor,2)
per_detractor

28.45

In [21]:
NPS=per_promoters-per_detractor
print(np.round(NPS,1))

23.7
